// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3r8ruYK9NLREszypFnYE5ksIPaNk4XGk',
    appId: '1:50180370934:web:bd63e3d4922a0ddc2e97d7',
    messagingSenderId: '50180370934',
    projectId: 'projectinformatika-4a6cf',
    authDomain: 'projectinformatika-4a6cf.firebaseapp.com',
    storageBucket: 'projectinformatika-4a6cf.appspot.com',
    measurementId: 'G-9MY5Z5TCWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYBNl1sKLnmPtRdXiPuB3AoWytxDBIpTY',
    appId: '1:50180370934:android:e23071cea314c70b2e97d7',
    messagingSenderId: '50180370934',
    projectId: 'projectinformatika-4a6cf',
    storageBucket: 'projectinformatika-4a6cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lO68BfS7mm6bDgnDOTIokMrqrZ2LvKI',
    appId: '1:50180370934:ios:f2f709c36438c0852e97d7',
    messagingSenderId: '50180370934',
    projectId: 'projectinformatika-4a6cf',
    storageBucket: 'projectinformatika-4a6cf.appspot.com',
    iosClientId: '50180370934-eo5c5hmfl8icvae7vduucedkpn7ccng2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikadesPi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lO68BfS7mm6bDgnDOTIokMrqrZ2LvKI',
    appId: '1:50180370934:ios:f2f709c36438c0852e97d7',
    messagingSenderId: '50180370934',
    projectId: 'projectinformatika-4a6cf',
    storageBucket: 'projectinformatika-4a6cf.appspot.com',
    iosClientId: '50180370934-eo5c5hmfl8icvae7vduucedkpn7ccng2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikadesPi',
  );
}
